apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  generateName: test-test-
  name: mongo
  labels:
    app: mongo
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      role: mongodb-shard1
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        role: mongodb-shard1
        tier: maindb
        replicaset: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongo
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
            - "--dbpath"
            - "/mongo-disk"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage 
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
