apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  generateName: test-test-
  name: omnicored 
  labels:
    app: omnicored
spec:
  replicas: {{ .Values.omnicored.replicaCount }}
  selector:
    matchLabels:
      role: omnicored-shard1
      app: omnicored
  template:
    metadata:
      labels:
        app: omnicored
        role: omnicored-shard1
        tier: maindb
        replicaset: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - omnicored
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: omnicored
          image: "{{ .Values.omnicored.image.repository }}:{{ .Values.omnicored.image.tag }}"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: bitcoind-data 
              mountPath: /bitcoind-disk
  volumeClaimTemplates:
  - metadata:
      name: bitcoind-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
