apiVersion: v1
kind: Service
metadata:
  generateName: test-test-
  name: omnicored
  labels:
    app: omnicored
spec:
  type: {{ .Values.omnicored.service.type }}
  ports:
    - name: port1
      port: 8332 
      targetPort: 8332
    - name: port2
      port: 8333
      targetPort: 8333
  selector:
    app: omnicored
