apiVersion: v1
kind: Service
metadata:
  generateName: test-test-
  name: swagger
  labels:
    app: swagger
spec:
  type: {{ .Values.swagger.service.type }}
  ports:
    - port: {{ .Values.swagger.service.port }}
      targetPort: {{ .Values.swagger.service.port }}
  selector:
    app: swagger 
