apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  generateName: test-test-
  name: swagger-ingress
  labels:
    app: swagger
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  backend:
    serviceName: swagger
    servicePort: {{ .Values.swagger.service.port }}
